import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Heading } from '@windswill/ui/components/Heading';
import { Text } from '@windswill/ui/components/Text';
import { Alert } from '@windswill/ui/components/Alert';
import { Button } from '@windswill/ui/components/Button';
export default function AlertSection() {
    const [dismissed, setDismissed] = useState(false);
    return (_jsxs("div", { children: [_jsx(Heading, { level: 1, children: "Alert" }), _jsx(Text, { variant: "muted", style: { marginBottom: 32 }, children: "Contextual feedback messages for user actions." }), _jsxs("section", { style: { marginBottom: 32 }, children: [_jsx(Heading, { level: 3, style: { marginBottom: 16 }, children: "Variants" }), _jsxs("div", { style: { display: 'flex', flexDirection: 'column', gap: 12 }, children: [_jsx(Alert, { variant: "info", title: "Information", children: "This is an informational alert." }), _jsx(Alert, { variant: "success", title: "Success", children: "Your changes have been saved." }), _jsx(Alert, { variant: "warning", title: "Warning", children: "Please review before proceeding." }), _jsx(Alert, { variant: "error", title: "Error", children: "Something went wrong. Please try again." })] })] }), _jsxs("section", { style: { marginBottom: 32 }, children: [_jsx(Heading, { level: 3, style: { marginBottom: 16 }, children: "With Dismiss" }), !dismissed && (_jsx(Alert, { variant: "info", title: "Dismissible Alert", children: _jsxs("div", { style: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '1rem' }, children: [_jsx(Text, { variant: "muted", children: "Click the \u00D7 to dismiss this alert." }), _jsx(Button, { size: "sm", variant: "ghost", onClick: () => setDismissed(true), children: "\u00D7" })] }) }))] }), _jsxs("section", { children: [_jsx(Heading, { level: 3, style: { marginBottom: 16 }, children: "With Action" }), _jsx(Alert, { variant: "success", title: "Changes saved", children: _jsxs("div", { style: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '1rem' }, children: [_jsx(Text, { variant: "muted", children: "Your profile has been updated." }), _jsx(Button, { size: "sm", children: "View" })] }) })] })] }));
}
