import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Heading } from '@windswill/ui/components/Heading';
import { Text } from '@windswill/ui/components/Text';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@windswill/ui/components/Tabs';
const tabs = ['Overview', 'Features', 'Pricing', 'Contact'];
export default function TabsSection() {
    const [activeTab, setActiveTab] = useState('Overview');
    return (_jsxs("div", { children: [_jsx(Heading, { level: 1, children: "Tabs" }), _jsx(Text, { variant: "muted", style: { marginBottom: 32 }, children: "Horizontal and vertical tab navigation for organizing content." }), _jsxs("section", { style: { marginBottom: 32 }, children: [_jsx(Heading, { level: 3, style: { marginBottom: 16 }, children: "Horizontal" }), _jsxs(Tabs, { defaultValue: "Overview", onChange: (value) => setActiveTab(value), children: [_jsx(TabsList, { children: tabs.map((tab) => (_jsx(TabsTrigger, { value: tab, children: tab }, tab))) }), _jsx(TabsContent, { value: "Overview", children: _jsxs(Text, { children: ["Content for: ", _jsx("strong", { children: "Overview" })] }) }), _jsx(TabsContent, { value: "Features", children: _jsxs(Text, { children: ["Content for: ", _jsx("strong", { children: "Features" })] }) }), _jsx(TabsContent, { value: "Pricing", children: _jsxs(Text, { children: ["Content for: ", _jsx("strong", { children: "Pricing" })] }) }), _jsx(TabsContent, { value: "Contact", children: _jsxs(Text, { children: ["Content for: ", _jsx("strong", { children: "Contact" })] }) })] })] }), _jsxs("section", { children: [_jsx(Heading, { level: 3, style: { marginBottom: 16 }, children: "Vertical" }), _jsx("div", { style: { display: 'flex', gap: 24 }, children: _jsxs(Tabs, { defaultValue: "Overview", children: [_jsx(TabsList, { style: { flexDirection: 'column', borderRight: '1px solid var(--color-border)', borderBottom: 'none', paddingRight: 16 }, children: tabs.map((tab) => (_jsx(TabsTrigger, { value: tab, style: { textAlign: 'left' }, children: tab }, tab))) }), _jsx(TabsContent, { value: "Overview", children: _jsxs(Text, { children: ["Vertical content: ", _jsx("strong", { children: "Overview" })] }) }), _jsx(TabsContent, { value: "Features", children: _jsxs(Text, { children: ["Vertical content: ", _jsx("strong", { children: "Features" })] }) }), _jsx(TabsContent, { value: "Pricing", children: _jsxs(Text, { children: ["Vertical content: ", _jsx("strong", { children: "Pricing" })] }) }), _jsx(TabsContent, { value: "Contact", children: _jsxs(Text, { children: ["Vertical content: ", _jsx("strong", { children: "Contact" })] }) })] }) })] })] }));
}
